### ISSUE TITLE
Pricing: highlight "Advanced plan"

### ISSUE THREAD

**Issue by humitos** [readthedocs/website#288]
We want to add some kind of distinction for the "Advanced plan". Show it with a different color or similar. Besides, add a "Recommended" or "Most valued" or similar...

This is the page we are talking about https://about.readthedocs.com/pricing/

**Comment by humitos** [comment]
Today I found this "Ribbon" that could be a good idea for this: https://semantic-ui.com/elements/label.html#ribbon

**Comment by agjohnson** [comment]
We had something similar at one point, and this might be worth trying. Howecer, the ribbon style will cause most of the content in the segment to shift down though. Instead, the content of the plans should be aligned vertically, otherwise it's more difficult to scan and compare. My first choice is likely content underneath the plan segment.
